# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.TextField(max_length=200)),
                ('place_id', models.IntegerField()),
                ('feedback_id', models.IntegerField()),
                ('feedback_by', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.TextField(max_length=200)),
                ('place_id', models.IntegerField()),
                ('feedback_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('placet_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('hotel_status', models.DateField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('hotel_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.TextField(max_length=200)),
                ('place_id', models.IntegerField()),
                ('like_status', models.TextField(max_length=200)),
                ('liked_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField(max_length=200)),
                ('Last_Name', models.TextField(max_length=200)),
                ('username', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('password', models.IntegerField()),
                ('password2', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('Login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.TextField(max_length=200)),
                ('place_number', models.IntegerField()),
                ('place_name', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('place_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField(max_length=200)),
                ('Last_Name', models.TextField(max_length=200)),
                ('username', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('password', models.IntegerField()),
                ('password2', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContinuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
