# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontinuation',
            name='email',
        ),
    ]
