# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190319_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContinuation',
        ),
    ]
