# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190320_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='full_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
