# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190320_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='message',
            new_name='message_1',
        ),
    ]
