# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20190320_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='userdata',
        ),
    ]
