# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_remove_contacts_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message_1',
            field=models.TextField(max_length=100),
        ),
    ]
