# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0002_auto_20190319_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='ph_no',
            field=models.CharField(max_length=200),
        ),
    ]
