# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('destination_details', models.TextField(max_length=200)),
                ('mainfactor', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/images')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('check_in', models.DateField(auto_now=True)),
                ('check_out', models.DateField(auto_now=True)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('check_in', models.DateField(auto_now=True)),
                ('check_out', models.DateField(auto_now=True)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
