# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190325_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('mainfactor', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/images')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
