# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo1',
            name='Destination_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
