# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_photo1_admin_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hlist',
            name='destination_details',
        ),
    ]
